import {
  Branch,
  Staff,
  ProductItem,
  IssueTypeConfig,
  EODRecord,
  ActionItem,
  RiskThresholds,
  RiskSettings,
} from '../types';

export const PASSCODE_HASHES = [
  '8fae968cc94c4353192d6993c65d92a43a6683de668960107c899a65191ef341', // eod-vtdua8 (Audit Staff 1)
  '80b09a7709e3ef167a11446bd2976a4f57d3ff1961e72d4e79e0965002d0f367', // eod-vaoz2z (Audit Staff 2)
];

export const USER_DIRECTORY = [
  { passcode: 'eod-vtdua8', slug: 'auditstaff1', name: 'Audit Staff 1' },
  { passcode: 'eod-vaoz2z', slug: 'auditstaff2', name: 'Audit Staff 2' },
];

export const STORAGE_KEYS = {
  BRANCHES: 'eod_matrix_branches_v3',
  STAFF: 'eod_matrix_staff_v3',
  ITEMS: 'eod_matrix_items_v3',
  ISSUE_TYPES: 'eod_matrix_issue_types_v3',
  RISK_SETTINGS: 'eod_matrix_risk_settings_v3',
  RISK_THRESHOLDS: 'eod_matrix_risk_thresholds_v3',
  THRESHOLDS: 'eod_matrix_risk_thresholds_v3',
  EOD_RECORDS: 'eod_matrix_records_v3',
  RECORDS: 'eod_matrix_records_v3',
  ACTION_ITEMS: 'eod_matrix_actions_v3',
  INCIDENTS: 'eod_matrix_incidents_v3',
  DISCIPLINARY_ACTIONS: 'eod_matrix_disciplinary_v3',
  DAILY_ENTRY_DRAFT: 'eod_matrix_daily_draft_v3',
  PASSCODE_SESSION: '__api_passcode',
  THEME_PREFS: '_uiprefs_theme',
};

export const INITIAL_BRANCHES: Branch[] = [
  { id: 'br-1', code: 'BR-01', name: 'CABANTIAN', active: true, region: 'Davao Region', createdAt: '2024-01-01' },
  { id: 'br-2', code: 'BR-02', name: 'AGTON', active: true, region: 'Davao Region', createdAt: '2024-01-01' },
  { id: 'br-3', code: 'BR-03', name: 'BALIOK', active: true, region: 'Davao Region', createdAt: '2024-01-01' },
  { id: 'br-4', code: 'BR-04', name: 'BANSALAN', active: true, region: 'Davao del Sur', createdAt: '2024-01-01' },
  { id: 'br-5', code: 'BR-05', name: 'CORONON', active: true, region: 'Davao del Sur', createdAt: '2024-01-01' },
  { id: 'br-6', code: 'BR-06', name: 'CROSSING BAYABAS', active: true, region: 'Davao Region', createdAt: '2024-01-01' },
  { id: 'br-7', code: 'BR-07', name: 'DIGOS APLAYA', active: true, region: 'Davao del Sur', createdAt: '2024-01-01' },
  { id: 'br-8', code: 'BR-08', name: 'KAPUTIAN', active: true, region: 'IGACOS', createdAt: '2024-01-01' },
  { id: 'br-9', code: 'BR-09', name: 'KM.5 BUHANGIN', active: true, region: 'Davao Region', createdAt: '2024-01-01' },
  { id: 'br-10', code: 'BR-10', name: 'MAKILALA 2', active: true, region: 'Cotabato', createdAt: '2024-01-01' },
  { id: 'br-11', code: 'BR-11', name: 'MAKILALA1', active: true, region: 'Cotabato', createdAt: '2024-01-01' },
  { id: 'br-12', code: 'BR-12', name: 'MANDUG', active: true, region: 'Davao Region', createdAt: '2024-01-01' },
  { id: 'br-13', code: 'BR-13', name: 'MIDSAYAP', active: true, region: 'Cotabato', createdAt: '2024-01-01' },
  { id: 'br-14', code: 'BR-14', name: 'MLANG', active: true, region: 'Cotabato', createdAt: '2024-01-01' },
  { id: 'br-15', code: 'BR-15', name: 'PADADA', active: true, region: 'Davao del Sur', createdAt: '2024-01-01' },
  { id: 'br-16', code: 'BR-16', name: 'PENAPLATA 1', active: true, region: 'IGACOS', createdAt: '2024-01-01' },
  { id: 'br-17', code: 'BR-17', name: 'PENAPLATA 2', active: true, region: 'IGACOS', createdAt: '2024-01-01' },
  { id: 'br-18', code: 'BR-18', name: 'SAMAL 1', active: true, region: 'IGACOS', createdAt: '2024-01-01' },
  { id: 'br-19', code: 'BR-19', name: 'SAMAL 2', active: true, region: 'IGACOS', createdAt: '2024-01-01' },
  { id: 'br-20', code: 'BR-20', name: 'SAN ANTONIO', active: true, region: 'Davao Region', createdAt: '2024-01-01' },
  { id: 'br-21', code: 'BR-21', name: 'SANDAWA', active: true, region: 'Davao Region', createdAt: '2024-01-01' },
  { id: 'br-22', code: 'BR-22', name: 'SULOP', active: true, region: 'Davao del Sur', createdAt: '2024-01-01' },
  { id: 'br-23', code: 'BR-23', name: 'SUNSCOR', active: true, region: 'Davao Region', createdAt: '2024-01-01' },
];

export const INITIAL_STAFF: Staff[] = [
  { id: 'cab-1', name: 'Mary Jane Saavedra', branch: 'CABANTIAN', position: 'Senior Cashier', phone: '0917-123-4501', email: 'mary.saavedra@bakeryeod.com', status: 'Active', joinedDate: '2024-01-15' },
  { id: 'cab-2', name: 'Jennefer Lara', branch: 'CABANTIAN', position: 'Cashier', phone: '0917-123-4502', status: 'Active', joinedDate: '2024-03-20' },
  { id: 'cab-3', name: 'Rubyliza Unibakers', branch: 'CABANTIAN', position: 'Cashier', phone: '0917-123-4503', status: 'Active', joinedDate: '2023-11-10' },
  { id: 'cab-4', name: 'Nohver Dacumos', branch: 'CABANTIAN', position: 'Team Lead', phone: '0917-123-4504', status: 'Active', joinedDate: '2024-05-02' },
  { id: 'cab-5', name: 'Jennette Taca', branch: 'CABANTIAN', position: 'Cashier', phone: '0917-123-4505', status: 'Active', joinedDate: '2024-02-18' },
  { id: 'agt-1', name: 'Anna Rose Timaan', branch: 'AGTON', position: 'Cashier', phone: '0918-555-0101', status: 'Active', joinedDate: '2024-02-01' },
  { id: 'agt-2', name: 'Honey Grace Allego', branch: 'AGTON', position: 'Team Lead', phone: '0918-555-0102', status: 'Active', joinedDate: '2024-01-10' },
  { id: 'bal-1', name: 'Rico Dela Cruz', branch: 'BALIOK', position: 'Cashier', status: 'Active', joinedDate: '2024-02-14' },
  { id: 'ban-1', name: 'Grace M. Mendoza', branch: 'BANSALAN', position: 'Cashier', status: 'Active', joinedDate: '2024-03-01' },
  { id: 'cor-1', name: 'Eduardo Tan', branch: 'CORONON', position: 'Cashier', status: 'Active', joinedDate: '2024-01-20' },
  { id: 'cro-1', name: 'Maritess Santos', branch: 'CROSSING BAYABAS', position: 'Senior Cashier', status: 'Active', joinedDate: '2024-02-11' },
  { id: 'dig-1', name: 'Rowena Alcantara', branch: 'DIGOS APLAYA', position: 'Cashier', status: 'Active', joinedDate: '2024-04-05' },
  { id: 'kap-1', name: 'Danilo Bautista', branch: 'KAPUTIAN', position: 'Cashier', status: 'Active', joinedDate: '2024-01-18' },
  { id: 'km5-1', name: 'Catherine Cruz', branch: 'KM.5 BUHANGIN', position: 'Cashier', status: 'Active', joinedDate: '2024-03-15' },
  { id: 'mak2-1', name: 'Leo Fernandez', branch: 'MAKILALA 2', position: 'Cashier', status: 'Active', joinedDate: '2024-02-22' },
  { id: 'mak1-1', name: 'Shiela Mae Ramos', branch: 'MAKILALA1', position: 'Cashier', status: 'Active', joinedDate: '2024-01-30' },
  { id: 'man-1', name: 'Vicente Morales', branch: 'MANDUG', position: 'Team Lead', status: 'Active', joinedDate: '2024-02-17' },
  { id: 'mid-1', name: 'Carmela Dizon', branch: 'MIDSAYAP', position: 'Cashier', status: 'Active', joinedDate: '2024-01-12' },
  { id: 'mla-1', name: 'Lito P. Reyes', branch: 'MLANG', position: 'Cashier', status: 'Active', joinedDate: '2024-03-10' },
  { id: 'pad-1', name: 'Jocelyn Navarro', branch: 'PADADA', position: 'Cashier', status: 'Active', joinedDate: '2024-02-05' },
  { id: 'pen1-1', name: 'Arlene Villanueva', branch: 'PENAPLATA 1', position: 'Cashier', status: 'Active', joinedDate: '2024-01-25' },
  { id: 'pen2-1', name: 'Gerardo Flores', branch: 'PENAPLATA 2', position: 'Cashier', status: 'Active', joinedDate: '2024-02-28' },
  { id: 'sam1-1', name: 'Ronalyn Castro', branch: 'SAMAL 1', position: 'Cashier', status: 'Active', joinedDate: '2024-03-12' },
  { id: 'sam2-1', name: 'Bernard Ocampo', branch: 'SAMAL 2', position: 'Cashier', status: 'Active', joinedDate: '2024-04-01' },
  { id: 'san-1', name: 'Kristine Joy Diaz', branch: 'SAN ANTONIO', position: 'Cashier', status: 'Active', joinedDate: '2024-01-19' },
  { id: 'sdw-1', name: 'Mark Anthony Perez', branch: 'SANDAWA', position: 'Senior Cashier', status: 'Active', joinedDate: '2024-02-10' },
  { id: 'sul-1', name: 'Gemma S. Cortez', branch: 'SULOP', position: 'Cashier', status: 'Active', joinedDate: '2024-03-08' },
  { id: 'sun-1', name: 'Alvin Miranda', branch: 'SUNSCOR', position: 'Cashier', status: 'Active', joinedDate: '2024-01-22' },
];

export const INITIAL_ITEMS: ProductItem[] = [
  { id: 'item-1', name: 'Pandesal Premium (Pack of 10)', code: 'FG-PAN-01', category: 'FG', defaultPrice: 50, active: true },
  { id: 'item-2', name: 'Ensaymada Special Supreme', code: 'FG-ENS-02', category: 'FG', defaultPrice: 65, active: true },
  { id: 'item-3', name: 'Classic Loaf Bread 450g', code: 'FG-LOA-03', category: 'FG', defaultPrice: 85, active: true },
  { id: 'item-4', name: 'Spanish Bread (Pack of 6)', code: 'FG-SPA-04', category: 'FG', defaultPrice: 48, active: true },
  { id: 'item-5', name: 'Cheese Bread Special (Pack of 8)', code: 'FG-CHZ-05', category: 'FG', defaultPrice: 55, active: true },
  { id: 'item-6', name: 'Ube Halaya Bread', code: 'FG-UBE-06', category: 'FG', defaultPrice: 75, active: true },
  { id: 'item-7', name: 'Bakery Hard Flour (25kg Bag)', code: 'RM-FLR-01', category: 'RM', defaultPrice: 1250, active: true },
  { id: 'item-8', name: 'Refined White Sugar (50kg Bag)', code: 'RM-SGR-02', category: 'RM', defaultPrice: 3400, active: true },
  { id: 'item-9', name: 'Pure Butter Margarine (15kg Tub)', code: 'RM-MAR-03', category: 'RM', defaultPrice: 1850, active: true },
  { id: 'item-10', name: 'Instant Dry Yeast 500g', code: 'RM-YST-04', category: 'RM', defaultPrice: 220, active: true },
  { id: 'item-11', name: 'Fresh Whole Eggs (Tray of 30)', code: 'RM-EGG-05', category: 'RM', defaultPrice: 260, active: true },
  { id: 'item-12', name: 'Evaporated Milk Culinary (1 Case)', code: 'RM-MLK-06', category: 'RM', defaultPrice: 1450, active: true },
  { id: 'item-13', name: 'Grated Cheddar Cheese 2kg', code: 'RM-CHZ-07', category: 'RM', defaultPrice: 680, active: true },
  { id: 'item-14', name: 'Choco Chip Filling 1kg', code: 'RM-CHO-08', category: 'RM', defaultPrice: 320, active: true },
];

export const INITIAL_ISSUE_TYPES: IssueTypeConfig[] = [
  { id: 'it-1', name: 'Wrong EOD', description: 'End-of-day register or inventory report calculation discrepancy', active: true, defaultCategory: 'EOD', defaultSeverity: 'High' },
  { id: 'it-2', name: 'Wrong Entry', description: 'Incorrect SKU, price override, or item quantity keying error', active: true, defaultCategory: 'Entry', defaultSeverity: 'Medium' },
  { id: 'it-3', name: 'Unpunch Item', description: 'Item physically issued/dispatched without POS transaction punch', active: true, defaultCategory: 'Item', defaultSeverity: 'High' },
  { id: 'it-4', name: 'Overpunch', description: 'Duplicate or excessive item quantity punched on customer receipt', active: true, defaultCategory: 'Item', defaultSeverity: 'Medium' },
  { id: 'it-5', name: 'Others', description: 'Uncategorized audit discrepancy, packaging loss, or system freeze', active: true, defaultCategory: 'General', defaultSeverity: 'Medium' },
];

export const DEFAULT_RISK_SETTINGS: RiskSettings = {
  financialThresholds: {
    medium: 500,
    high: 1500,
    critical: 3000,
  },
  repeatIncidentThreshold: 3,
  repeatIncidentWindowDays: 7,
  trendAlertThresholdPercent: 20,
  riskScoreThresholds: {
    lowMax: 39,
    mediumMax: 59,
    highMax: 79,
    criticalMin: 80,
  },
  weights: {
    financialExposure: 40,
    issueFrequency: 30,
    repeatIncidents: 20,
    unresolvedIssues: 10,
  },
};

export const DEFAULT_RISK_THRESHOLDS: RiskThresholds = {
  criticalLoss: 3000,
  highLoss: 1500,
  moderateLoss: 500,
  consecutiveErrorCount: 3,
  criticalStaffRiskScore: 80,
  highStaffRiskScore: 60,
  moderateStaffRiskScore: 30,
  staffWeightFinancialLoss: 40,
  staffWeightIncidentFrequency: 30,
  staffWeightRepeatBehavior: 20,
  staffWeightUnresolvedActions: 10,
};

export const INITIAL_EOD_RECORDS: EODRecord[] = [
  {
    id: 'eod-101',
    date: '2026-08-25',
    branch: 'CABANTIAN',
    staffId: 'cab-1',
    staffName: 'Mary Jane Saavedra',
    issueType: 'Overpunch',
    varianceStatus: 'Y',
    department: 'FG',
    items: [
      { id: 'row-1', itemId: 'item-2', itemName: 'Ensaymada Special Supreme', quantity: 4, unitPrice: 65, totalPrice: 260 },
      { id: 'row-2', itemId: 'item-3', itemName: 'Classic Loaf Bread 450g', quantity: 2, unitPrice: 85, totalPrice: 170 },
    ],
    totalFinancialImpact: 430,
    rootCause: 'Staff Error',
    remarks: 'Customer checkout queue rush resulted in duplicate punch of 4 Ensaymadas.',
    createdAt: '2026-08-25T18:30:00Z',
  },
  {
    id: 'eod-102',
    date: '2026-08-24',
    branch: 'CABANTIAN',
    staffId: 'cab-2',
    staffName: 'Jennefer Lara',
    issueType: 'Unpunch Item',
    varianceStatus: 'R',
    department: 'FG',
    items: [
      { id: 'row-3', itemId: 'item-6', itemName: 'Ube Halaya Bread', quantity: 6, unitPrice: 75, totalPrice: 450 },
      { id: 'row-4', itemId: 'item-1', itemName: 'Pandesal Premium (Pack of 10)', quantity: 8, unitPrice: 50, totalPrice: 400 },
    ],
    totalFinancialImpact: 850,
    rootCause: 'Training Needed',
    remarks: 'Dispatched display rack replenishment without printing shift dispatch voucher.',
    createdAt: '2026-08-24T19:15:00Z',
  },
  {
    id: 'eod-103',
    date: '2026-08-23',
    branch: 'AGTON',
    staffId: 'agt-1',
    staffName: 'Anna Rose Timaan',
    issueType: 'Wrong EOD',
    varianceStatus: 'R',
    department: 'RM',
    items: [
      { id: 'row-5', itemId: 'item-7', itemName: 'Bakery Hard Flour (25kg Bag)', quantity: 2, unitPrice: 1250, totalPrice: 2500 },
      { id: 'row-6', itemId: 'item-8', itemName: 'Refined White Sugar (50kg Bag)', quantity: 1, unitPrice: 3400, totalPrice: 3400 },
    ],
    totalFinancialImpact: 5900,
    rootCause: 'Staff Error',
    remarks: 'Closing raw ingredient physical stock count differed heavily from shift receiving register.',
    createdAt: '2026-08-23T20:00:00Z',
  },
  {
    id: 'eod-104',
    date: '2026-08-22',
    branch: 'AGTON',
    staffId: 'agt-1',
    staffName: 'Anna Rose Timaan',
    issueType: 'Wrong Entry',
    varianceStatus: 'Y',
    department: 'FG',
    items: [
      { id: 'row-7', itemId: 'item-2', itemName: 'Ensaymada Special Supreme', quantity: 10, unitPrice: 65, totalPrice: 650 },
      { id: 'row-8', itemId: 'item-4', itemName: 'Spanish Bread (Pack of 6)', quantity: 5, unitPrice: 48, totalPrice: 240 },
    ],
    totalFinancialImpact: 890,
    rootCause: 'Staff Error',
    remarks: 'Barcoded item price keyed as standard bread instead of supreme ensaymada.',
    createdAt: '2026-08-22T17:40:00Z',
  },
  {
    id: 'eod-105',
    date: '2026-08-21',
    branch: 'MIDSAYAP',
    staffId: 'mid-1',
    staffName: 'Carmela Dizon',
    issueType: 'Wrong EOD',
    varianceStatus: 'R',
    department: 'RM',
    items: [
      { id: 'row-9', itemId: 'item-8', itemName: 'Refined White Sugar (50kg Bag)', quantity: 1, unitPrice: 3400, totalPrice: 3400 },
      { id: 'row-10', itemId: 'item-9', itemName: 'Pure Butter Margarine (15kg Tub)', quantity: 1, unitPrice: 1850, totalPrice: 1850 },
    ],
    totalFinancialImpact: 5250,
    rootCause: 'System Issue',
    remarks: 'POS network timeout during final EOD batch transmission; variance flagged.',
    createdAt: '2026-08-21T21:10:00Z',
  },
  {
    id: 'eod-106',
    date: '2026-08-20',
    branch: 'CABANTIAN',
    staffId: 'cab-1',
    staffName: 'Mary Jane Saavedra',
    issueType: 'Overpunch',
    varianceStatus: 'Y',
    department: 'FG',
    items: [
      { id: 'row-11', itemId: 'item-5', itemName: 'Cheese Bread Special (Pack of 8)', quantity: 6, unitPrice: 55, totalPrice: 330 },
      { id: 'row-12', itemId: 'item-1', itemName: 'Pandesal Premium (Pack of 10)', quantity: 5, unitPrice: 50, totalPrice: 250 },
    ],
    totalFinancialImpact: 580,
    rootCause: 'Staff Error',
    remarks: 'Keyed double quantity on catering bulk sale.',
    createdAt: '2026-08-20T16:20:00Z',
  },
  {
    id: 'eod-107',
    date: '2026-08-19',
    branch: 'CABANTIAN',
    staffId: 'cab-1',
    staffName: 'Mary Jane Saavedra',
    issueType: 'Wrong Entry',
    varianceStatus: 'Y',
    department: 'FG',
    items: [
      { id: 'row-13', itemId: 'item-3', itemName: 'Classic Loaf Bread 450g', quantity: 5, unitPrice: 85, totalPrice: 425 },
      { id: 'row-14', itemId: 'item-6', itemName: 'Ube Halaya Bread', quantity: 3, unitPrice: 75, totalPrice: 225 },
    ],
    totalFinancialImpact: 650,
    rootCause: 'Training Needed',
    remarks: 'Used old price matrix code for loaf breads.',
    createdAt: '2026-08-19T14:15:00Z',
  },
  {
    id: 'eod-108',
    date: '2026-08-18',
    branch: 'BANSALAN',
    staffId: 'ban-1',
    staffName: 'Grace M. Mendoza',
    issueType: 'Unpunch Item',
    varianceStatus: 'Y',
    department: 'FG',
    items: [
      { id: 'row-15', itemId: 'item-4', itemName: 'Spanish Bread (Pack of 6)', quantity: 8, unitPrice: 48, totalPrice: 384 },
      { id: 'row-16', itemId: 'item-2', itemName: 'Ensaymada Special Supreme', quantity: 3, unitPrice: 65, totalPrice: 195 },
    ],
    totalFinancialImpact: 579,
    rootCause: 'Staff Error',
    remarks: 'Handed bread packs to delivery rider without scanning barcoded bag tags.',
    createdAt: '2026-08-18T11:00:00Z',
  },
  {
    id: 'eod-109',
    date: '2026-08-17',
    branch: 'KM.5 BUHANGIN',
    staffId: 'km5-1',
    staffName: 'Catherine Cruz',
    issueType: 'Wrong EOD',
    varianceStatus: 'R',
    department: 'RM',
    items: [
      { id: 'row-17', itemId: 'item-7', itemName: 'Bakery Hard Flour (25kg Bag)', quantity: 1, unitPrice: 1250, totalPrice: 1250 },
      { id: 'row-18', itemId: 'item-10', itemName: 'Instant Dry Yeast 500g', quantity: 4, unitPrice: 220, totalPrice: 880 },
    ],
    totalFinancialImpact: 2130,
    rootCause: 'Staff Error',
    remarks: 'Flour sack torn in delivery bay not marked as damaged inventory.',
    createdAt: '2026-08-17T09:30:00Z',
  },
  {
    id: 'eod-110',
    date: '2026-08-16',
    branch: 'SANDAWA',
    staffId: 'sdw-1',
    staffName: 'Mark Anthony Perez',
    issueType: 'Wrong Entry',
    varianceStatus: 'Y',
    department: 'FG',
    items: [
      { id: 'row-19', itemId: 'item-1', itemName: 'Pandesal Premium (Pack of 10)', quantity: 12, unitPrice: 50, totalPrice: 600 },
      { id: 'row-20', itemId: 'item-5', itemName: 'Cheese Bread Special (Pack of 8)', quantity: 4, unitPrice: 55, totalPrice: 220 },
    ],
    totalFinancialImpact: 820,
    rootCause: 'Staff Error',
    remarks: 'Manual discount code misapplication on wholesale morning pickup.',
    createdAt: '2026-08-16T08:15:00Z',
  },
  {
    id: 'eod-111',
    date: '2026-08-15',
    branch: 'BALIOK',
    staffId: 'bal-1',
    staffName: 'Rico Dela Cruz',
    issueType: 'Others',
    varianceStatus: 'Y',
    department: 'FG',
    items: [
      { id: 'row-21', itemId: 'item-3', itemName: 'Classic Loaf Bread 450g', quantity: 6, unitPrice: 85, totalPrice: 510 },
      { id: 'row-22', itemId: 'item-2', itemName: 'Ensaymada Special Supreme', quantity: 4, unitPrice: 65, totalPrice: 260 },
    ],
    totalFinancialImpact: 770,
    rootCause: 'Item Setup Problem',
    remarks: 'PLU barcode tag mismatch in database after weekend system sync.',
    createdAt: '2026-08-15T15:00:00Z',
  },
];

export const INITIAL_ACTION_ITEMS: ActionItem[] = [
  {
    id: 'act-1',
    recordId: 'eod-103',
    branch: 'AGTON',
    staffName: 'Anna Rose Timaan',
    date: '2026-08-23',
    issueType: 'Wrong EOD',
    priority: 'Critical',
    assignedTo: 'Honey Grace Allego',
    actionRequired: 'Conduct complete physical bread stock audit and recount at the bakeshop display racks and storage area to verify against EOD sales report.',
    status: 'Open',
    dueDate: '2026-08-28',
    notes: 'Audit team requested re-weighing of open bulk ingredient containers.',
    createdAt: '2026-08-23T20:30:00Z',
  },
  {
    id: 'act-2',
    recordId: 'eod-101',
    branch: 'CABANTIAN',
    staffName: 'Mary Jane Saavedra',
    date: '2026-08-25',
    issueType: 'Overpunch',
    priority: 'High',
    assignedTo: 'Nohver Dacumos',
    actionRequired: 'Conduct 1-on-1 cashier refresher training on rush-hour queue voiding and dual-checking receipts.',
    status: 'In Progress',
    dueDate: '2026-08-27',
    notes: 'Training module assigned; pending completion signature.',
    createdAt: '2026-08-25T19:00:00Z',
  },
  {
    id: 'act-3',
    recordId: 'eod-105',
    branch: 'MIDSAYAP',
    staffName: 'Carmela Dizon',
    date: '2026-08-21',
    issueType: 'Wrong EOD',
    priority: 'High',
    assignedTo: 'Area Supervisor',
    actionRequired: 'Reconfigure POS offline queue sync and test network switch buffer.',
    status: 'In Progress',
    dueDate: '2026-08-29',
    notes: 'IT technician dispatched to replace router network cable.',
    createdAt: '2026-08-21T21:40:00Z',
  },
  {
    id: 'act-4',
    recordId: 'eod-102',
    branch: 'CABANTIAN',
    staffName: 'Jennefer Lara',
    date: '2026-08-24',
    issueType: 'Unpunch Item',
    priority: 'Medium',
    assignedTo: 'Nohver Dacumos',
    actionRequired: 'Verify display rack replenishment physical logs against morning dispatch receipts.',
    status: 'Resolved',
    dueDate: '2026-08-26',
    completionDate: '2026-08-26',
    notes: 'Physical dispatch slips reconciled and entered manually into ERP system.',
    createdAt: '2026-08-24T20:00:00Z',
  },
];
